while(True):
    n=int(input())
    if(n==0):
        break
    c=list(map(int,input().split()))
    s=list(map(int,input().split()))
    c.sort(reverse=True)
    s.sort(reverse=True)
    i0=0
    j0=0
    i1=n-1
    j1=n-1
    maxs=0
    maxc=0
    while(i0<=i1 and j0<=j1):
        if(s[i0]>c[j0]):
            maxs+=3
            i0+=1
            j0+=1
        elif(s[i0]<c[j0]):
            maxs+=1
            i1-=1
            j0+=1
        else:
            if(s[i1]>c[j1]):
                maxs+=3
                i1-=1
                j1-=1
            else:
                if(s[i1]<c[j0]):
                    maxs+=1
                    i1-=1
                    j0+=1
                else:
                    maxs+=2
                    i0+=1
                    j0+=1
    i0=0
    j0=0
    i1=n-1
    j1=n-1
    while(i0<=i1 and j0<=j1):
        if(c[i0]>s[j0]):
            maxc+=3
            i0+=1
            j0+=1
        elif(c[i0]<s[j0]):
            maxc+=1
            i1-=1
            j0+=1
        else:
            if(c[i1]>s[j1]):
                maxc+=3
                i1-=1
                j1-=1
            else:
                if(c[i1]<s[j0]):
                    maxc+=1
                    i1-=1
                    j0+=1
                else:
                    maxc+=2
                    i0+=1
                    j0+=1
    print(maxs,4*n-maxc)